name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: yeswanth-63
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
